theme = "oxocarbon"

[keys.normal.space.u]
r = ":config-reload"
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"

[editor]
# end-of-line-diagnostics = "hint"
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]

[editor.inline-diagnostics]
cursor-line = "error"

# create a new minor mode bound to `+`
[keys.normal."+"]
m = ":run-shell-command echo 2"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"
n = ":run-shell-command echo 3"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
