# Oxocarbon with Enhanced LSP Gutter Icons

# Syntax Highlighting
"attribute" = { fg = "#82cfff" }
"type" = { fg = "#78a9ff" }
"type.return" = { fg = "#78a9ff" }
"type.parameter" = { fg = "#a8cc7c" }
"constructor" = { fg = "#78a9ff" }
"constant" = { fg = "#be95ff" }
"string" = { fg = "#e394dc" }
"comment" = { fg = "#525252", modifiers = ["italic"] }
"variable" = { fg = "#dde1e6" }
"keyword" = { fg = "#78a9ff" }
"function" = { fg = "#ff7eb6" }
"tag" = { fg = "#78a9ff" }

# LSP Diagnostics (Text)
"diagnostic.error" = { fg = "#FF6F6A", underline = { color = "#FF6F6A", style = "curl" } }
"diagnostic.warning" = { fg = "#F3AA60", underline = { color = "#F3AA60", style = "curl" } }
"diagnostic.info" = { fg = "#82CFFF", underline = { color = "#82CFFF", style = "curl" } }
"diagnostic.hint" = { fg = "#A8CC7C", underline = { color = "#A8CC7C", style = "curl" } }
"diagnostic.unnecessary" = { fg = "#525252", modifiers = ["dim"] }
"diagnostic.deprecated" = { fg = "#FF7EB6", modifiers = ["crossed_out"] }

# Gutter Icon Colors
"hint" = "A8CC7C"
"info" = "#82CFFF"
"warning" = "#F3AA60"
"error" = "#FF6F6A"
"gutter.diagnostic.error" = { fg = "#FF6F6A" }      # Red icon for errors
"gutter.diagnostic.warning" = { fg = "#F3AA60" }    # Orange icon for warnings
"gutter.diagnostic.info" = { fg = "#82CFFF" }       # Blue icon for info
"gutter.diagnostic.hint" = { fg = "#A8CC7C" }       # Green icon for hints

# UI Elements
"ui.background" = { bg = "#161616" }
"ui.linenr" = { fg = "#525252", bg = "#161616" }
"ui.linenr.selected" = { fg = "#dde1e6" }
"ui.cursorline" = { bg = "#262626" }

# Selection
"ui.selection" = { bg = "#393939" }                 # Active selection
"ui.selection.primary" = { bg = "#525252" }         # Highlighted selection

# Inlay Hints
"ui.virtual.inlay-hint" = { fg = "#b3b3b3", bg = "#262626", modifiers = ["italic"] }

# Diff
"diff.plus" = { fg = "#42be65", bg = "#393939" }
"diff.minus" = { fg = "#78a9ff", bg = "#393939" }
