"attribute" = "#42be65"

"type" = "#78a9ff"
"type.return" = "#82cfff"
"type.parameter" = "#82cfff"

"constructor" = "#82cfff"

"constant" = "#be95ff"
"constant.builtin.boolean" = "#3ddbd9"
"constant.character" = "#82cfff"
"constant.character.escape" = "#3ddbd9"
"constant.numeric" = "#82cfff"
  
"string" = "#ff7eb6"
"string.regexp" = "#3ddbd9"
"string.special" = { fg = "#82cfff", modifiers = ["underlined"] }

"comment" = "#525252"

"variable" = "#cccccc"
"variable.builtin" = { fg = "#ff7f50" }
"variable.other.member" = "#be95ff"
  
"label" = "#82cfff"
  
"keyword" = "#3ddbd9"
  
"function" = "#82cfff"
"function.declaration" = "#efefef"
"function.macro" = "#42be65"
"function.builtin" = "#42be65"
"function.special" = "#42be65"
  
"tag" = "#78a9ff"
  
"special" = "#42be65"
  
"namespace" = "#78a9ff"
  
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.heading" = { fg = "#3ddbd9", modifiers = ["bold"] }
"markup.list" = "#ff7eb6"
  
"markup.list.numbered" = "#3ddbd9"
"markup.list.unnumbered" = "#3ddbd9"
"markup.link.url" = { fg = "#ff7eb6", modifiers = ["italic", "underlined"] }
"markup.link.text" = "#3ddbd9"
"markup.link.label" = "#e8daff"
"markup.quote" = "#ff7eb6"
"markup.raw" = "#ff7eb6"
"markup.raw.inline" = "#3ddbd9"
"markup.raw.block" = "#EB83E2"
  
"diff.plus" = "#42be65"
"diff.minus" = "#78a9ff"
"diff.delta" = "#78a9ff"
  
"ui.background" = { bg = "#161616" }
"ui.statusline" = { fg = "#cccccc", bg = "#262626" }
"ui.statusline.normal" = { fg = "#cccccc", bg = "#262626" }
"ui.statusline.inactive" = { fg = "#525252" }
"ui.statusline.insert" = { fg = "#262626", bg = "#001d6c" }
"ui.statusline.select" = { fg = "#262626", bg = "#82cfff" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "#a6c8ff" }
"ui.selection" = { bg = "#393939" }
"ui.selection.primary" = { bg = "#78a9ff" }
"ui.cursorline" = { bg = "#1f1f1f" }
"ui.linenr" = "#3c3c3c"
"ui.linenr.selected" = "#b3b3b3"
"ui.popup" = { fg = "#cccccc", bg = "#262626" }
"ui.window" = { fg = "#393939" }
"ui.help" = { fg = "#cccccc", bg = "#262626" }
"ui.menu" = { fg = "#cccccc", bg = "#262626" }
"ui.menu.selected" = { fg = "#ffffff", bg = "#78a9ff" }
"ui.menu.scroll" = { fg = "#dfdfdf" }
"ui.text" = "#cccccc"
"ui.text.focus" = { fg = "#ffffff", bg = "#78a9ff" }
"ui.virtual" = "#525252"
"ui.virtual.inlay-hint" = { fg = "#3c3c3c" }
"ui.virtual.ruler" = { bg = "#262626" }

"hint" = "#6f6f6f"
"info" = "#A366C4"
"warning" = "#FACb66"
"error" = "#FF5269"

"diagnostic.hint" = { underline = { color = "#6f6f6f", style = "line" } }
"diagnostic.info" = { underline = { color = "#A366C4", style = "line" } }
"diagnostic.warning" = { underline = { color = "#FACb66", style = "line" } }
"diagnostic.error" = { underline = { color = "#FF5269", style = "line" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

